name: "CI/CD - Implantação Cluster"

on:
  push:
    branches: [ "dev", "homolog", "main" ]
  pull_request:
    branches: [ "homolog", "main" ]

jobs:
  validacao-pre-commit:
    name: "Validar Pre-Commit"
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"

      - name: Executar hooks do Pre-Commit
        uses: pre-commit/action@v3.0.1

  terraform-deploy:
    name: "Terraform Apply"
    needs: validacao-pre-commit
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v4

      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"

      - name: Inicializar Terraform
        run: terraform init

      - name: Aplicar Infraestrutura
        env:
          TFVARS_cidr_block: ${{ secrets.TFVARS_CIDR_BLOCK }}
          TFVARS_project_name: ${{ secrets.TFVARS_PROJECT_NAME}}
        run: terraform apply -auto-approve -input=false
